spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_hh?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
